name: Create Q1_archive_README

on:
  push:
    branches:
      - main

jobs:
  create-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Create Q1_archive_README.md
      run: |
        cp README.md Q1_archive_README.md

    - name: Configure Git
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"

    - name: Commit and push changes
      run: |
        git add Q1_archive_README.md
        git commit -m "Add Q1_archive_README.md"
        git push
