name: Create Q2_archive_README

on:
  push:
    branches:
      - main

jobs:
  create-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Create Q2_archive_README.md
      run: |
        echo "Ledoux Gaétan" > Q2_archive_README.md
        echo " " > Q2_archive_README.md
        echo "Date et heure d'exécution : $(date)" >> Q2_archive_README.md
        echo "" >> Q2_archive_README.md
        cat README.md >> Q2_archive_README.md

    - name: Configure Git
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"

    - name: Commit and push changes
      run: |
        git add Q2_archive_README.md
        git commit -m "Add Q2_archive_README.md"
        git push
